# Docker Compose
# https://docs.docker.com/compose/

version: '3.6'
services:
  # Python
  app:
    environment: &environment
      - STAGE=local
    image: cookiecutter-next-redux-saga-app-dev
    build:
      args:
        stage: dev

  nodejs:
    ports:
      - '3000:3000'
    restart: always
    image: cookiecutter-next-redux-saga-node-dev
    build:
      context: .
      dockerfile: provision/docker/nodejs/Dockerfile
      args:
        stage: dev
    volumes:
      - .:/usr/src
      - yarn-cache:/root/.yarn-cache
    env_file:
      - .env

  check:
    image: cookiecutter-next-redux-saga-check-dev
    environment: *environment
    build:
      context: .
      dockerfile: provision/docker/check/Dockerfile
      args:
        stage: dev
    volumes:
      - .:/usr/src
    env_file:
      - .env
